WITH ventas_base AS (
    SELECT
        ID_VENTA,
        ID_CLIENTE,
        FECHA_VENTA,
        TOTAL,
        ESTADO
    FROM {{ ref('ventas_base') }}
)

SELECT
    EXTRACT(YEAR FROM FECHA_VENTA) AS ANIO,
    EXTRACT(MONTH FROM FECHA_VENTA) AS MES,
    SUM(TOTAL) AS TOTAL_VENTAS
FROM ventas_base
WHERE ESTADO = 'COMPLETADA'
GROUP BY EXTRACT(YEAR FROM FECHA_VENTA), EXTRACT(MONTH FROM FECHA_VENTA)
ORDER BY ANIO DESC, MES DESC
